services:
  tuws:
    build: .
    container_name: be_flask_tuws
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - TZ=Asia/Jakarta
    networks:
      - backend_tuws
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis_tuws
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    environment:
      - TZ=Asia/Jakarta
    networks:
      - backend_tuws
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    restart: always
    container_name: db_postgres_tuws
    environment:
      POSTGRES_DB: tuws_prod_db
      POSTGRES_USER: tuws_prod
      POSTGRES_PASSWORD: TuwsSecretPassword!
      TZ: Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tuws_prod -d tuws_prod_db -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_tuws

volumes:
  postgres_data:
  redis_data:

networks:
  backend_tuws:
    driver: bridge