"""Initial Migrate and Seeding Data

Revision ID: 40f14e08573e
Revises: 
Create Date: 2025-12-17 01:54:29.932292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f14e08573e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('range_prediction', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weather_log_ecowitt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vpd_outdoor', sa.Float(), nullable=True),
    sa.Column('temperature_main_outdoor', sa.Float(), nullable=True),
    sa.Column('temperature_feels_like_outdoor', sa.Float(), nullable=True),
    sa.Column('temperature_apparent_outdoor', sa.Float(), nullable=True),
    sa.Column('dew_point_outdoor', sa.Float(), nullable=True),
    sa.Column('humidity_outdoor', sa.Float(), nullable=True),
    sa.Column('temperature_main_indoor', sa.Float(), nullable=True),
    sa.Column('temperature_feels_like_indoor', sa.Float(), nullable=True),
    sa.Column('temperature_apparent_indoor', sa.Float(), nullable=True),
    sa.Column('dew_point_indoor', sa.Float(), nullable=True),
    sa.Column('humidity_indoor', sa.Float(), nullable=True),
    sa.Column('solar_irradiance', sa.Float(), nullable=True),
    sa.Column('uvi', sa.Float(), nullable=True),
    sa.Column('rain_rate', sa.Float(), nullable=True),
    sa.Column('rain_daily', sa.Float(), nullable=True),
    sa.Column('rain_event', sa.Float(), nullable=True),
    sa.Column('rain_hour', sa.Float(), nullable=True),
    sa.Column('rain_weekly', sa.Float(), nullable=True),
    sa.Column('rain_monthly', sa.Float(), nullable=True),
    sa.Column('rain_yearly', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('pressure_relative', sa.Float(), nullable=True),
    sa.Column('pressure_absolute', sa.Float(), nullable=True),
    sa.Column('battery_sensor_array', sa.Float(), nullable=True),
    sa.Column('request_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_log_wunderground',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solar_radiation', sa.Float(), nullable=True),
    sa.Column('ultraviolet_radiation', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('precipitation_rate', sa.Float(), nullable=True),
    sa.Column('precipitation_total', sa.Float(), nullable=True),
    sa.Column('request_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weather_log_wunderground_id', sa.Integer(), nullable=True),
    sa.Column('weather_log_ecowitt_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('ecowitt_prediction_result', sa.Integer(), nullable=True),
    sa.Column('wunderground_prediction_result', sa.Integer(), nullable=True),
    sa.Column('ecowitt_prediction_data', sa.JSON(), nullable=True),
    sa.Column('wunderground_prediction_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ecowitt_prediction_result'], ['label.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['weather_log_ecowitt_id'], ['weather_log_ecowitt.id'], ),
    sa.ForeignKeyConstraint(['weather_log_wunderground_id'], ['weather_log_wunderground.id'], ),
    sa.ForeignKeyConstraint(['wunderground_prediction_result'], ['label.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_log')
    op.drop_table('weather_log_wunderground')
    op.drop_table('weather_log_ecowitt')
    op.drop_table('model')
    op.drop_table('label')
    # ### end Alembic commands ###
