"""init

Revision ID: f59d834029ba
Revises: 
Create Date: 2026-02-24 13:51:39.068886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f59d834029ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_lstm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weather_log_console_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('weather_log_ecowitt_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('weather_log_wunderground_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lstm_prediction_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('console_result', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('ecowitt_result', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('wunderground_result', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('range_prediction', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weather_log_console',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('heap', sa.Integer(), nullable=True),
    sa.Column('temperature_indoor', sa.Float(), nullable=True),
    sa.Column('humidity_indoor', sa.Float(), nullable=True),
    sa.Column('pressure_relative', sa.Float(), nullable=True),
    sa.Column('pressure_absolute', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('max_daily_gust', sa.Float(), nullable=True),
    sa.Column('solar_radiation', sa.Float(), nullable=True),
    sa.Column('uvi', sa.Float(), nullable=True),
    sa.Column('rain_rate', sa.Float(), nullable=True),
    sa.Column('rain_event', sa.Float(), nullable=True),
    sa.Column('rain_hourly', sa.Float(), nullable=True),
    sa.Column('rain_daily', sa.Float(), nullable=True),
    sa.Column('rain_weekly', sa.Float(), nullable=True),
    sa.Column('rain_monthly', sa.Float(), nullable=True),
    sa.Column('rain_yearly', sa.Float(), nullable=True),
    sa.Column('rain_total', sa.Float(), nullable=True),
    sa.Column('vpd', sa.Float(), nullable=True),
    sa.Column('date_utc', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_log_console', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_log_console_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_log_console_date_utc'), ['date_utc'], unique=True)

    op.create_table('weather_log_ecowitt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vpd_outdoor', sa.Float(), nullable=True),
    sa.Column('temperature_main_outdoor', sa.Float(), nullable=True),
    sa.Column('temperature_feels_like_outdoor', sa.Float(), nullable=True),
    sa.Column('temperature_apparent_outdoor', sa.Float(), nullable=True),
    sa.Column('dew_point_outdoor', sa.Float(), nullable=True),
    sa.Column('humidity_outdoor', sa.Float(), nullable=True),
    sa.Column('temperature_main_indoor', sa.Float(), nullable=True),
    sa.Column('temperature_feels_like_indoor', sa.Float(), nullable=True),
    sa.Column('temperature_apparent_indoor', sa.Float(), nullable=True),
    sa.Column('dew_point_indoor', sa.Float(), nullable=True),
    sa.Column('humidity_indoor', sa.Float(), nullable=True),
    sa.Column('solar_irradiance', sa.Float(), nullable=True),
    sa.Column('uvi', sa.Float(), nullable=True),
    sa.Column('rain_rate', sa.Float(), nullable=True),
    sa.Column('rain_daily', sa.Float(), nullable=True),
    sa.Column('rain_event', sa.Float(), nullable=True),
    sa.Column('rain_hour', sa.Float(), nullable=True),
    sa.Column('rain_weekly', sa.Float(), nullable=True),
    sa.Column('rain_monthly', sa.Float(), nullable=True),
    sa.Column('rain_yearly', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('pressure_relative', sa.Float(), nullable=True),
    sa.Column('pressure_absolute', sa.Float(), nullable=True),
    sa.Column('battery_sensor_array', sa.Float(), nullable=True),
    sa.Column('request_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_log_ecowitt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_log_ecowitt_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_log_ecowitt_request_time'), ['request_time'], unique=True)

    op.create_table('weather_log_wunderground',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solar_radiation', sa.Float(), nullable=True),
    sa.Column('ultraviolet_radiation', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('precipitation_rate', sa.Float(), nullable=True),
    sa.Column('precipitation_total', sa.Float(), nullable=True),
    sa.Column('request_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_log_wunderground', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_log_wunderground_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_log_wunderground_request_time'), ['request_time'], unique=True)

    op.create_table('data_xgboost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weather_log_console_id', sa.Integer(), nullable=True),
    sa.Column('weather_log_ecowitt_id', sa.Integer(), nullable=True),
    sa.Column('weather_log_wunderground_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['weather_log_console_id'], ['weather_log_console.id'], ),
    sa.ForeignKeyConstraint(['weather_log_ecowitt_id'], ['weather_log_ecowitt.id'], ),
    sa.ForeignKeyConstraint(['weather_log_wunderground_id'], ['weather_log_wunderground.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_xgboost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_xgboost_weather_log_console_id'), ['weather_log_console_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_xgboost_weather_log_ecowitt_id'), ['weather_log_ecowitt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_xgboost_weather_log_wunderground_id'), ['weather_log_wunderground_id'], unique=False)

    op.create_table('xgboost_prediction_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('console_result_id', sa.Integer(), nullable=True),
    sa.Column('ecowitt_result_id', sa.Integer(), nullable=True),
    sa.Column('wunderground_result_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['console_result_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['ecowitt_result_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['wunderground_result_id'], ['label.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('xgboost_prediction_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xgboost_prediction_result_console_result_id'), ['console_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_xgboost_prediction_result_ecowitt_result_id'), ['ecowitt_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_xgboost_prediction_result_wunderground_result_id'), ['wunderground_result_id'], unique=False)

    op.create_table('prediction_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('data_xgboost_id', sa.Integer(), nullable=True),
    sa.Column('data_lstm_id', sa.Integer(), nullable=True),
    sa.Column('xgboost_result_id', sa.Integer(), nullable=True),
    sa.Column('lstm_result_id', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['data_lstm_id'], ['data_lstm.id'], ),
    sa.ForeignKeyConstraint(['data_xgboost_id'], ['data_xgboost.id'], ),
    sa.ForeignKeyConstraint(['lstm_result_id'], ['lstm_prediction_result.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['xgboost_result_id'], ['xgboost_prediction_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_log_data_lstm_id'), ['data_lstm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_log_data_xgboost_id'), ['data_xgboost_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_log_lstm_result_id'), ['lstm_result_id'], unique=False)
        batch_op.create_index('ix_prediction_log_model_created', ['model_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_log_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_log_xgboost_result_id'), ['xgboost_result_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_log_xgboost_result_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_log_model_id'))
        batch_op.drop_index('ix_prediction_log_model_created')
        batch_op.drop_index(batch_op.f('ix_prediction_log_lstm_result_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_log_data_xgboost_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_log_data_lstm_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_log_created_at'))

    op.drop_table('prediction_log')
    with op.batch_alter_table('xgboost_prediction_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xgboost_prediction_result_wunderground_result_id'))
        batch_op.drop_index(batch_op.f('ix_xgboost_prediction_result_ecowitt_result_id'))
        batch_op.drop_index(batch_op.f('ix_xgboost_prediction_result_console_result_id'))

    op.drop_table('xgboost_prediction_result')
    with op.batch_alter_table('data_xgboost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_xgboost_weather_log_wunderground_id'))
        batch_op.drop_index(batch_op.f('ix_data_xgboost_weather_log_ecowitt_id'))
        batch_op.drop_index(batch_op.f('ix_data_xgboost_weather_log_console_id'))

    op.drop_table('data_xgboost')
    with op.batch_alter_table('weather_log_wunderground', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_log_wunderground_request_time'))
        batch_op.drop_index(batch_op.f('ix_weather_log_wunderground_created_at'))

    op.drop_table('weather_log_wunderground')
    with op.batch_alter_table('weather_log_ecowitt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_log_ecowitt_request_time'))
        batch_op.drop_index(batch_op.f('ix_weather_log_ecowitt_created_at'))

    op.drop_table('weather_log_ecowitt')
    with op.batch_alter_table('weather_log_console', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_log_console_date_utc'))
        batch_op.drop_index(batch_op.f('ix_weather_log_console_created_at'))

    op.drop_table('weather_log_console')
    op.drop_table('model')
    op.drop_table('lstm_prediction_result')
    op.drop_table('label')
    op.drop_table('data_lstm')
    # ### end Alembic commands ###
